import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  keyboardContainer: {
    flex: 1,
  },
  keyboardScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  card: {
    borderRadius: 30,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 20,
    shadowColor: '#111',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.16,
    shadowRadius: 24,
    elevation: 8,
  },
  brandContainer: {
    alignItems: 'center',
    marginBottom: 14,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  brandText: {
    color: '#1A3F6F',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 3,
  },
  brandPinWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5A623',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  brandSubtitle: {
    marginTop: 4,
    color: '#F5A623',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  welcomeWrap: {
    alignItems: 'center',
    marginBottom: 18,
  },
  welcomeTitle: {
    color: '#1A3F6F',
    fontSize: 21,
    fontWeight: '800',
  },
  welcomeSubtitle: {
    marginTop: 4,
    color: '#9aa3b2',
    fontSize: 13,
  },
  fieldBlock: {
    marginBottom: 13,
  },
  label: {
    fontSize: 12,
    marginBottom: 6,
    fontWeight: '700',
    color: '#1A3F6F',
  },
  inputWrap: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e8ebf2',
    backgroundColor: '#f8f9fb',
    minHeight: 47,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputControl: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    minHeight: 44,
  },
  input: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e8ebf2',
    backgroundColor: '#f8f9fb',
    paddingHorizontal: 13,
    minHeight: 47,
    fontSize: 14,
    color: '#333',
  },
  inputError: {
    borderColor: '#E8453C',
    backgroundColor: '#FFF5F5',
  },
  errorText: {
    color: '#E8453C',
    marginTop: 4,
    fontSize: 11,
  },
  passwordContainer: {
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#e8ebf2',
    backgroundColor: '#f8f9fb',
    minHeight: 47,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
    gap: 10,
  },
  passwordInput: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    minHeight: 44,
  },
  ctaButton: {
    marginTop: 6,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#F5A623',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 14,
    elevation: 5,
  },
  ctaText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '800',
  },
  ctaButtonDisabled: {
    opacity: 0.75,
  },
  separatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#eee',
  },
  separatorText: {
    fontSize: 11,
    color: '#bbb',
    fontWeight: '600',
  },
  switchText: {
    marginTop: 14,
    textAlign: 'center',
    color: '#F5A623',
    fontSize: 13,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    justifyContent: 'center',
    paddingHorizontal: 22,
  },
  modalCard: {
    borderRadius: 20,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  modalTitle: {
    color: '#23283a',
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 8,
  },
  modalMessage: {
    color: '#4b5165',
    fontSize: 14,
    marginBottom: 14,
  },
  modalButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalButton: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  modalButtonSecondary: {
    backgroundColor: '#edf0f8',
  },
  modalButtonPrimary: {
    backgroundColor: '#1e74c6',
  },
  modalButtonTextSecondary: {
    color: '#36415c',
    fontWeight: '700',
    fontSize: 13,
  },
  modalButtonTextPrimary: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
});
