import { StyleSheet } from 'react-native';

export const bankAccountsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#0f6dbb',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#f59e0b', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 90 },
  title: { color: '#0f4f85', fontSize: 28, fontWeight: '800', marginBottom: 10 },
  searchInput: {
    borderWidth: 1,
    borderColor: '#e5e6ef',
    borderRadius: 12,
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#273143',
    marginBottom: 12,
    backgroundColor: '#fff',
  },
  clientCard: {
    borderWidth: 1,
    borderColor: '#ececf5',
    borderRadius: 14,
    backgroundColor: '#fff',
    minHeight: 78,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  clientCardSelected: { borderColor: '#0f6dbb', borderWidth: 2 },
  clientIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#dbeefd',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  clientBody: { flex: 1 },
  clientName: { color: '#0f5f9f', fontWeight: '800', fontSize: 16 },
  clientSubtitle: { color: '#4a5060', fontSize: 13, marginTop: 2 },

  primaryButton: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: '#0f6dbb',
    borderRadius: 12,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: { color: '#fff', fontSize: 17, fontWeight: '800' },

  accountsTitle: {
    color: '#0f4f85',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 6,
    marginBottom: 8,
  },
  accountCard: {
    borderWidth: 1,
    borderColor: '#e6e7f0',
    borderRadius: 12,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  accountLine: { color: '#2f3446', fontSize: 14, marginBottom: 2 },
  accountLabel: { fontWeight: '800', color: '#0f5f9f' },
  accountActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  smallBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtn: { backgroundColor: '#0f6dbb' },
  deleteBtn: { backgroundColor: '#ef4040' },
  smallBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ececf3',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 16,
  },
  bottomIconWrap: { width: 56, height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  bottomIconWrapActive: {
    width: 56,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#0f6dbb',
    alignItems: 'center',
    justifyContent: 'center',
  },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', paddingHorizontal: 14 },
  modalCard: { borderRadius: 14, backgroundColor: '#fff', paddingHorizontal: 14, paddingVertical: 14, maxHeight: '92%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalTitle: { color: '#0f5f9f', fontSize: 20, fontWeight: '800' },
  fieldLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 8,
  },
  pickerButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 8,
  },
  pickerButtonText: { color: '#263143', fontSize: 15 },
  pickerListInline: { borderWidth: 1, borderColor: '#e1e4ef', borderRadius: 10, backgroundColor: '#fff', marginBottom: 8 },

  bankSearchInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#eceff7',
    minHeight: 40,
    paddingHorizontal: 12,
    color: '#263143',
    marginBottom: 4,
  },
  pickerModalCard: {
    borderRadius: 14,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 14,
    maxHeight: '75%',
  },
  pickerScroll: { maxHeight: 320 },
  pickerItem: { paddingHorizontal: 12, paddingVertical: 10 },
  pickerItemText: { color: '#2a3144', fontSize: 14 },

  deleteMessage: { color: '#33394b', fontSize: 15, marginBottom: 10 },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
  emptyText: { color: '#666b7a', fontSize: 13, marginTop: 10 },

  modalActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 8 },
  modalActionBtn: {
    minWidth: 120,
    borderRadius: 12,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalConfirmBtn: { backgroundColor: '#1e74c6' },
  deleteBtnModal: { backgroundColor: '#ef4040' },
  modalCancelBtn: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#dfe3ef' },
  modalActionBtnText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  modalCancelBtnText: { color: '#1f2433', fontWeight: '800', fontSize: 15 },
});
