import { StyleSheet } from 'react-native';

export const bankAccountsClientStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#0f6dbb',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#f59e0b', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 10 },
  pageHeaderRow: { marginBottom: 8 },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: '#eaf4fc',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  backBtnText: { color: '#0f5f9f', fontWeight: '700', fontSize: 13 },
  title: { color: '#0f4f85', fontSize: 22, fontWeight: '800', marginBottom: 4 },
  subtitle: { color: '#5a6071', fontSize: 14, fontWeight: '700', marginBottom: 10 },

  searchInput: {
    borderWidth: 1,
    borderColor: '#e5e6ef',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#273143',
    marginBottom: 10,
    backgroundColor: '#fff',
  },

  loadingWrap: { alignItems: 'center', justifyContent: 'center', paddingTop: 30 },
  listContent: { paddingBottom: 20 },
  accountCard: {
    borderWidth: 1,
    borderColor: '#e6e7f0',
    borderRadius: 12,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  accountLine: { color: '#2f3446', fontSize: 13, marginBottom: 2 },
  accountLabel: { fontWeight: '800', color: '#0f5f9f' },
  actionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 8 },
  actionBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtn: { backgroundColor: '#0f6dbb' },
  deleteBtn: { backgroundColor: '#ef4040' },
  actionText: { color: '#fff', fontWeight: '700', fontSize: 13 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 14,
    maxHeight: '92%',
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalTitle: { color: '#0f5f9f', fontSize: 19, fontWeight: '800' },
  fieldLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#263143',
    marginBottom: 8,
  },
  modalInputDisabled: { backgroundColor: '#f2f3f8', color: '#8b90a1' },
  pickerButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 8,
  },
  pickerButtonText: { color: '#263143', fontSize: 14 },
  pickerListInline: {
    borderWidth: 1,
    borderColor: '#e1e4ef',
    borderRadius: 10,
    backgroundColor: '#fff',
    marginBottom: 8,
  },
  pickerItem: { paddingHorizontal: 12, paddingVertical: 10 },
  pickerItemText: { color: '#2a3144', fontSize: 14 },
  pickerModalCard: {
    borderRadius: 14,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 14,
    maxHeight: '75%',
  },
  bankSearchInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#eceff7',
    minHeight: 40,
    paddingHorizontal: 12,
    color: '#263143',
    marginBottom: 4,
  },
  pickerScroll: { maxHeight: 320 },

  deleteMessage: { color: '#33394b', fontSize: 15, marginBottom: 10 },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
  emptyText: { color: '#666b7a', fontSize: 13, marginTop: 10 },
  modalActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 8 },
  modalActionBtn: {
    minWidth: 120,
    borderRadius: 12,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalConfirmBtn: { backgroundColor: '#1e74c6' },
  deleteBtnModal: { backgroundColor: '#ef4040' },
  modalCancelBtn: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#dfe3ef' },
  modalActionBtnText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  modalCancelBtnText: { color: '#1f2433', fontWeight: '800', fontSize: 15 },
});
