import { StyleSheet } from 'react-native';

export const bankAccountsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#f59e0b',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#d97706', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 140 },
  titleBlock: { marginBottom: 12 },
  titleOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 1,
  },
  title: { color: '#0f4f85', fontSize: 28, fontWeight: '800' },
  titleHint: { fontSize: 12, color: '#999', marginTop: 2 },

  searchWrap: {
    borderWidth: 1.5,
    borderColor: '#eee',
    borderRadius: 12,
    minHeight: 46,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 15, color: '#273143' },
  searchClear: { opacity: 0.4, fontSize: 13 },

  list: { flex: 1 },
  listContent: { paddingBottom: 6 },

  clientCard: {
    borderWidth: 1,
    borderColor: '#ececf5',
    borderLeftWidth: 4,
    borderLeftColor: '#F5A623',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  clientIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f59e0b',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  clientIconText: { color: '#ffffff', fontWeight: '800', fontSize: 13 },
  clientBody: { flex: 1 },
  clientName: { color: '#0f5f9f', fontWeight: '800', fontSize: 16 },
  clientSubtitle: { color: '#4a5060', fontSize: 13, marginTop: 2 },
  clientBadges: { alignItems: 'flex-end', gap: 4 },
  countBadge: { backgroundColor: '#EAF2FF', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 2 },
  countBadgeText: { color: '#2563A8', fontSize: 10, fontWeight: '700' },
  clientChevron: { color: '#bbb', fontSize: 14, fontWeight: '700' },

  emptyText: { color: '#666b7a', fontSize: 13, marginTop: 10 },

  primaryButtonWrap: { position: 'absolute', left: 16, right: 16, bottom: 92 },
  primaryButton: {
    backgroundColor: '#f59e0b',
    borderRadius: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 7,
  },
  primaryButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '800' },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 8,
    paddingBottom: 16,
  },
  bottomTab: { alignItems: 'center', gap: 4, minWidth: 64 },
  bottomTabIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  bottomTabIconActive: { backgroundColor: '#FFF0D6' },
  bottomTabText: { fontSize: 10, fontWeight: '700', color: '#a6aab6' },
  bottomTabTextActive: { color: '#f59e0b' },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', paddingHorizontal: 14 },
  modalCard: {
    borderRadius: 24,
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 22,
    maxHeight: '88%',
  },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modalTitle: { color: '#0f5f9f', fontSize: 20, fontWeight: '800' },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F2F4F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#263143',
    marginBottom: 10,
  },
  selectorBtn: {
    borderWidth: 1.5,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#f2f4f7',
    minHeight: 44,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 10,
  },
  selectorBtnText: { color: '#263143', fontSize: 14, fontWeight: '600' },

  chipsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  typeChip: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F2F4F7',
  },
  typeChipActive: { backgroundColor: '#f5a623' },
  typeChipText: { color: '#555', fontWeight: '700', fontSize: 11 },
  typeChipTextActive: { color: '#fff' },

  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
  modalActionsRow: { flexDirection: 'row', gap: 10, marginTop: 6 },
  modalActionBtn: {
    borderRadius: 14,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalConfirmBtn: { backgroundColor: '#1e74c6', flex: 2 },
  modalCancelBtn: { backgroundColor: '#EEF0F6', flex: 1 },
  modalActionBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  modalCancelBtnText: { color: '#2f2e67', fontWeight: '800', fontSize: 14 },

  sheetBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheetCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingBottom: 20,
    maxHeight: '72%',
  },
  sheetHandle: { width: 44, height: 4, borderRadius: 4, backgroundColor: '#ddd', alignSelf: 'center', marginTop: 10, marginBottom: 10 },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  sheetTitle: { color: '#1A3F6F', fontSize: 17, fontWeight: '800' },
  sheetScroll: { maxHeight: 320 },
  sheetItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ececf5',
    backgroundColor: '#fff',
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetItemText: { color: '#2a3144', fontSize: 14, fontWeight: '700', flex: 1, marginRight: 8 },
});
