import { StyleSheet } from 'react-native';

export const bankAccountsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: { backgroundColor: '#5b3db3', paddingTop: 22, paddingBottom: 18, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#7f5ae1', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  content: { flex: 1, paddingHorizontal: 16, paddingTop: 14, paddingBottom: 90 },
  title: { color: '#35257c', fontSize: 28, fontWeight: '800', marginBottom: 10 },
  searchInput: { borderWidth: 1, borderColor: '#e5e6ef', borderRadius: 12, minHeight: 46, paddingHorizontal: 14, fontSize: 15, color: '#273143', marginBottom: 12, backgroundColor: '#fff' },
  clientCard: { borderWidth: 1, borderColor: '#ececf5', borderRadius: 14, backgroundColor: '#fff', minHeight: 78, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 10, flexDirection: 'row', alignItems: 'center' },
  clientCardSelected: { borderColor: '#7c59d7', borderWidth: 2 },
  clientIconWrap: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#d7beff', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  clientBody: { flex: 1 },
  clientName: { color: '#3b2f7c', fontWeight: '800', fontSize: 16 },
  clientSubtitle: { color: '#4a5060', fontSize: 13, marginTop: 2 },
  emptyText: { color: '#666b7a', fontSize: 13, marginTop: 10 },
  primaryButton: { marginTop: 8, marginBottom: 6, backgroundColor: '#7c59d7', borderRadius: 12, minHeight: 54, alignItems: 'center', justifyContent: 'center' },
  primaryButtonText: { color: '#fff', fontSize: 18, fontWeight: '800' },
  bottomBar: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#ececf3', flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10, paddingBottom: 16 },
  bottomIconWrap: { width: 56, height: 46, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  bottomIconWrapActive: { width: 56, height: 46, borderRadius: 12, backgroundColor: '#7c59d7', alignItems: 'center', justifyContent: 'center' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', paddingHorizontal: 14 },
  modalCard: { borderRadius: 14, backgroundColor: '#fff', paddingHorizontal: 14, paddingVertical: 14, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalTitle: { color: '#3b2f7c', fontSize: 20, fontWeight: '800' },
  fieldLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  modalInput: { borderWidth: 1, borderColor: '#dfe3ef', borderRadius: 12, backgroundColor: '#fff', minHeight: 44, paddingHorizontal: 14, fontSize: 15, color: '#263143', marginBottom: 8 },
  readonlyField: { borderWidth: 1, borderColor: '#dfe3ef', borderRadius: 12, backgroundColor: '#f5f6fb', minHeight: 44, paddingHorizontal: 14, justifyContent: 'center', marginBottom: 8 },
  readonlyFieldText: { color: '#334', fontWeight: '700', fontSize: 13 },
  pickerButton: { borderWidth: 1, borderColor: '#dfe3ef', borderRadius: 12, backgroundColor: '#fff', minHeight: 44, paddingHorizontal: 14, justifyContent: 'center', marginBottom: 8 },
  pickerButtonText: { color: '#263143', fontSize: 15 },
  pickerList: { borderWidth: 1, borderColor: '#e1e4ef', borderRadius: 10, backgroundColor: '#fff', marginBottom: 8 },
  pickerListLarge: { borderWidth: 1, borderColor: '#e1e4ef', borderRadius: 10, backgroundColor: '#fff', marginBottom: 8, maxHeight: 200 },
  bankSearchInput: { borderBottomWidth: 1, borderBottomColor: '#eceff7', minHeight: 40, paddingHorizontal: 12, color: '#263143' },
  pickerItem: { paddingHorizontal: 12, paddingVertical: 10 },
  pickerItemText: { color: '#2a3144', fontSize: 14 },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
  modalActionsRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 8 },
  modalActionBtn: { minWidth: 120, borderRadius: 12, minHeight: 46, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  modalConfirmBtn: { backgroundColor: '#bfaef1' },
  modalCancelBtn: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#dfe3ef' },
  modalActionBtnText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  modalCancelBtnText: { color: '#1f2433', fontWeight: '800', fontSize: 15 },
});
