import { StyleSheet } from 'react-native';

export const bankAccountsClientStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#f59e0b',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#d97706', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 },
  titleOverline: { fontSize: 11, color: '#F5A623', fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  title: { color: '#0f4f85', fontSize: 22, fontWeight: '800' },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#EAF2FF', borderRadius: 20, paddingVertical: 7, paddingHorizontal: 12 },
  backDot: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#1A3F6F', alignItems: 'center', justifyContent: 'center' },
  backBtnText: { color: '#1A3F6F', fontWeight: '700', fontSize: 12 },

  clientHeaderCard: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  clientAvatar: { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.25)', alignItems: 'center', justifyContent: 'center' },
  clientAvatarText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  clientHeaderName: { color: '#fff', fontWeight: '800', fontSize: 13, flex: 1, marginLeft: 10 },
  clientCountPill: { backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 3 },
  clientCountText: { color: '#fff', fontSize: 11, fontWeight: '700' },

  searchWrap: {
    borderWidth: 1.5,
    borderColor: '#eee',
    borderRadius: 12,
    minHeight: 46,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 14, color: '#273143' },
  searchClear: { opacity: 0.4, fontSize: 13 },

  loadingWrap: { alignItems: 'center', justifyContent: 'center', paddingTop: 30 },
  listContent: { paddingBottom: 20 },
  accountCard: {
    borderWidth: 1,
    borderColor: '#ececf5',
    borderLeftWidth: 4,
    borderLeftColor: '#F5A623',
    borderRadius: 16,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  accountTopRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  accountAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#f5a623', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  accountAvatarText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  accountBody: { flex: 1 },
  accountName: { color: '#0f5f9f', fontWeight: '800', fontSize: 14 },
  accountSub: { color: '#4a5060', fontSize: 12 },
  clientChevron: { color: '#bbb', fontSize: 14, fontWeight: '700' },
  accountInfoWrap: { marginBottom: 8 },
  accountInfoLine: { color: '#2f3446', fontSize: 12, marginBottom: 2 },
  accountInfoLabel: { fontWeight: '800', color: '#0f5f9f' },

  actionsRow: { flexDirection: 'row', gap: 8, borderTopWidth: 1, borderTopColor: '#f2f3f7', paddingTop: 8 },
  actionBtn: { flex: 1, minHeight: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  editBtn: { backgroundColor: '#EAF2FF' },
  deleteBtn: { backgroundColor: '#FFE8E7' },
  actionText: { fontSize: 12, fontWeight: '700', color: '#2563A8' },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', paddingHorizontal: 14 },
  modalCard: { borderRadius: 24, backgroundColor: '#fff', paddingHorizontal: 20, paddingVertical: 22, maxHeight: '88%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  modalOverline: { fontSize: 11, color: '#F5A623', fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase' },
  modalTitle: { color: '#0f5f9f', fontSize: 20, fontWeight: '800' },
  modalCloseBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#F2F4F7', alignItems: 'center', justifyContent: 'center' },
  fieldLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  readOnlyCard: {
    borderWidth: 1.5,
    borderColor: '#e6ebf2',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#f2f4f7',
    marginBottom: 10,
  },
  readOnlyText: { color: '#8b90a1', fontWeight: '700', letterSpacing: 0.6, fontSize: 13 },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#263143',
    marginBottom: 10,
  },
  selectorBtn: {
    borderWidth: 1.5,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#f2f4f7',
    minHeight: 44,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 10,
  },
  selectorBtnText: { color: '#263143', fontSize: 14, fontWeight: '600' },

  chipsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  typeChip: { borderRadius: 10, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: '#F2F4F7' },
  typeChipActive: { backgroundColor: '#f5a623' },
  typeChipText: { color: '#555', fontWeight: '700', fontSize: 11 },
  typeChipTextActive: { color: '#fff' },

  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
  emptyText: { color: '#666b7a', fontSize: 13, marginTop: 10 },

  modalActionsRow: { flexDirection: 'row', gap: 10, marginTop: 6 },
  modalActionBtn: { borderRadius: 14, minHeight: 50, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  modalConfirmBtn: { backgroundColor: '#1e74c6', flex: 2 },
  modalCancelBtn: { backgroundColor: '#EEF0F6', flex: 1 },
  modalActionBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  modalCancelBtnText: { color: '#2f2e67', fontWeight: '800', fontSize: 14 },

  sheetBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheetCard: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 16, paddingBottom: 20, maxHeight: '72%' },
  sheetHandle: { width: 44, height: 4, borderRadius: 4, backgroundColor: '#ddd', alignSelf: 'center', marginTop: 10, marginBottom: 10 },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  sheetTitle: { color: '#1A3F6F', fontSize: 17, fontWeight: '800' },
  sheetScroll: { maxHeight: 320 },
  sheetItem: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ececf5',
    backgroundColor: '#fff',
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetItemText: { color: '#2a3144', fontSize: 14, fontWeight: '700', flex: 1, marginRight: 8 },

  deleteModalCardModern: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: 'center',
  },
  deleteIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFE8E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  deleteIconText: { fontSize: 26 },
  deleteOverline: {
    fontSize: 11,
    color: '#E8453C',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  deleteModalTitle: { color: '#1f2433', fontSize: 22, fontWeight: '800' },
  deleteModalMessage: {
    color: '#666',
    fontSize: 13,
    lineHeight: 22,
    marginVertical: 14,
    textAlign: 'center',
  },
  deleteModalStrong: { color: '#E8453C', fontWeight: '800' },
  deleteActionsRow: { flexDirection: 'row', gap: 10, width: '100%' },
  deleteBtnModal: {
    backgroundColor: '#ef4040',
    flex: 2,
    borderRadius: 14,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelBtn: {
    backgroundColor: '#EEF0F6',
    flex: 1,
    borderRadius: 14,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteConfirmText: { color: '#fff', fontWeight: '800', fontSize: 14 },
  deleteCancelText: { color: '#2f2e67', fontWeight: '800', fontSize: 14 },
});
