import { StyleSheet } from 'react-native';

export const entrepreneursStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fb',
  },
  header: {
    backgroundColor: '#5b3db3',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: {
    width: 102,
    height: 82,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoutButton: {
    backgroundColor: '#7f5ae1',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 90,
  },
  title: {
    color: '#35257c',
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 10,
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#e5e6ef',
    borderRadius: 12,
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#273143',
    marginBottom: 12,
    backgroundColor: '#ffffff',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 14,
  },
  swipeGhostAction: {
    marginBottom: 12,
    width: 24,
  },
  clientCard: {
    borderWidth: 1,
    borderColor: '#ececf5',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    minHeight: 88,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  clientIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#d7beff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  clientBody: {
    flex: 1,
  },
  clientName: {
    color: '#3b2f7c',
    fontWeight: '800',
    fontSize: 17,
  },
  clientSubtitle: {
    color: '#4a5060',
    fontSize: 14,
    marginTop: 2,
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 13,
    marginTop: 10,
  },
  primaryButton: {
    marginTop: 8,
    marginBottom: 6,
    backgroundColor: '#7c59d7',
    borderRadius: 12,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#ececf3',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 16,
  },
  bottomIconWrapActive: {
    width: 56,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#7c59d7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomIconWrap: {
    width: 56,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: '#3b2f7c',
    fontSize: 22,
    fontWeight: '800',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#263143',
    marginBottom: 6,
  },
  modalInputError: {
    borderColor: '#cc4a59',
    borderWidth: 2,
  },
  errorText: {
    color: '#c2475b',
    fontSize: 13,
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 12,
  },
  modalActionBtn: {
    minWidth: 130,
    borderRadius: 12,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalConfirmBtn: {
    backgroundColor: '#bfaef1',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dfe3ef',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 17,
  },
  modalCancelBtnText: {
    color: '#1f2433',
    fontWeight: '800',
    fontSize: 17,
  },

  deleteModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  deleteModalTitle: {
    color: '#1f2433',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#2e3442',
    fontSize: 17,
    lineHeight: 32,
    marginVertical: 16,
  },
  deleteModalStrong: {
    color: '#1f2433',
    fontWeight: '800',
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  deleteBtn: {
    minWidth: 130,
    borderRadius: 12,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#1f2433',
    fontSize: 17,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
});
