import { StyleSheet } from 'react-native';

export const entrepreneursStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fb',
  },
  header: {
    backgroundColor: '#f59e0b',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: {
    width: 102,
    height: 82,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoutButton: {
    backgroundColor: '#d97706',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  title: {
    color: '#0f4f85',
    fontSize: 28,
    fontWeight: '800',
  },
  titleBlock: {
    marginBottom: 12,
  },
  titleOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 1,
  },
  titleHint: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  searchWrap: {
    borderWidth: 1.5,
    borderColor: '#eee',
    borderRadius: 12,
    minHeight: 46,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#273143',
  },
  searchClear: { opacity: 0.4, fontSize: 13 },
  homeListWrap: {
    height: '68%',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 20,
  },
  swipeGhostAction: {
    marginBottom: 10,
    width: 24,
  },
  clientCard: {
    borderWidth: 1,
    borderColor: '#ececf5',
    borderLeftWidth: 4,
    borderLeftColor: '#F5A623',
    borderRadius: 16,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  clientTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  clientIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f59e0b',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  clientIconText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 13,
  },
  clientBody: {
    flex: 1,
  },
  clientName: {
    color: '#0f5f9f',
    fontWeight: '800',
    fontSize: 16,
  },
  clientSubtitle: {
    color: '#4a5060',
    fontSize: 13,
    marginTop: 2,
  },
  clientBadges: {
    alignItems: 'flex-end',
    gap: 4,
  },
  clientChevron: {
    color: '#bbb',
    fontSize: 14,
    fontWeight: '700',
  },
  badgeNotified: {
    backgroundColor: '#E8F8F0',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    color: '#1A9E5C',
    fontSize: 9,
    fontWeight: '700',
  },
  badgeCharge: {
    backgroundColor: '#FFF4E5',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    color: '#E08A00',
    fontSize: 9,
    fontWeight: '700',
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 13,
    marginTop: 10,
  },
  primaryButtonWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 92,
  },
  primaryButton: {
    backgroundColor: '#f59e0b',
    borderRadius: 16,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F5A623',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 7,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 8,
    paddingBottom: 16,
  },
  bottomTab: {
    alignItems: 'center',
    gap: 4,
    minWidth: 64,
  },
  bottomTabIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  bottomTabIconActive: {
    backgroundColor: '#FFF0D6',
  },
  bottomTabText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#a6aab6',
  },
  bottomTabTextActive: {
    color: '#f59e0b',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalCardAdd: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 24,
  },
  modalCardEdit: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    color: '#0f5f9f',
    fontSize: 20,
    fontWeight: '800',
  },
  modalOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F2F4F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editAvatarWrap: {
    alignItems: 'center',
    marginBottom: 16,
  },
  editAvatarCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editAvatarText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#263143',
    marginBottom: 6,
  },
  modalInputError: {
    borderColor: '#cc4a59',
    borderWidth: 2,
  },

  editFormScroll: {
    maxHeight: 360,
  },
  editFormContent: {
    paddingBottom: 4,
  },
  switchRow: {
    marginTop: 6,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F9FB',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  switchTextWrap: {
    flex: 1,
    marginRight: 12,
  },
  switchHint: {
    color: '#999',
    fontSize: 10,
    fontWeight: '500',
  },
  phoneInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F4F7',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#eee',
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  phonePrefix: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F5A623',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  phoneInput: {
    flex: 1,
    minHeight: 44,
    fontSize: 16,
    color: '#263143',
    paddingHorizontal: 8,
  },
  datePickerButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#e6e8ee',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 56,
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  datePickerButtonIcon: {
    fontSize: 16,
  },
  datePickerButtonText: {
    flex: 1,
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '700',
  },
  datePickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  clearDateButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#eceef8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    color: '#c2475b',
    fontSize: 13,
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#1e74c6',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },

  deleteModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  deleteModalCardModern: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: 'center',
  },
  deleteIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFE8E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  deleteIconText: { fontSize: 26 },
  deleteOverline: {
    fontSize: 11,
    color: '#E8453C',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  deleteModalTitle: {
    color: '#1f2433',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#666',
    fontSize: 13,
    lineHeight: 22,
    marginVertical: 14,
    textAlign: 'center',
  },
  deleteModalStrong: {
    color: '#E8453C',
    fontWeight: '800',
  },
  deleteClientInfoCard: {
    backgroundColor: '#FFF4E5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  deleteClientAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteClientAvatarText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 12,
  },
  deleteClientName: {
    flex: 1,
    color: '#1A3F6F',
    fontWeight: '700',
    fontSize: 13,
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  deleteBtn: {
    minWidth: 130,
    borderRadius: 12,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#1f2433',
    fontSize: 17,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },

  calendarModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pickerTitle: {
    color: '#1a3f6f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f2f4f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    color: '#1a3f6f',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthTitle: {
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  calendarWeekDay: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#f5a623',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  calendarDayCell: {
    width: '14.2857%',
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#f5a623',
  },
  calendarDayText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },
});
