import { StyleSheet } from 'react-native';

export const entrepreneurAccountStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fb',
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  topHeader: {
    height: 30,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  topCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#0f5f9f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 10,
  },
  titleBlock: {
    marginTop: 4,
    marginBottom: 12,
  },
  titleOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  nameCard: {
    backgroundColor: '#c8b4ef',
    borderRadius: 12,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    paddingHorizontal: 14,
    gap: 10,
    marginBottom: 12,
  },
  nameAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameAvatarText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  nameCardText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    flex: 1,
  },
  datesRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  dateCol: {
    flex: 1,
    minHeight: 82,
  },
  dateLabel: {
    fontSize: 10,
    color: '#9aa0ad',
    fontWeight: '600',
    marginBottom: 4,
    paddingLeft: 4,
  },
  dateInputButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderColor: '#e6e8ee',
    borderWidth: 1.5,
    borderRadius: 12,
    minHeight: 56,
    paddingHorizontal: 14,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  dateInputButtonIcon: {
    fontSize: 16,
  },
  dateInputButtonText: {
    flex: 1,
    fontSize: 14,
    color: '#1a3f6f',
    fontWeight: '700',
  },
  dateInputButtonActive: {
    borderColor: '#f5a623',
  },
  salesCard: {
    backgroundColor: '#d97706',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  salesTitle: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 18,
  },
  salesValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
  },
  reportRow: {
    marginBottom: 10,
  },
  reportBtn: {
    backgroundColor: '#1A3F6F',
    borderRadius: 12,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  swipeGhostAction: {
    marginBottom: 14,
    width: 24,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderLeftWidth: 4,
    borderLeftColor: '#F5A623',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f59e0b',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  body: {
    flex: 1,
  },
  titleText: {
    color: '#293040',
    fontSize: 16,
    fontWeight: '800',
  },
  subtitleText: {
    color: '#1f6fb2',
    fontSize: 13,
    fontWeight: '700',
  },
  dateText: {
    color: '#6f7383',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  amountIncome: {
    color: '#2e9d68',
    fontSize: 15,
    fontWeight: '800',
  },
  amountExpense: {
    color: '#c85353',
    fontSize: 15,
    fontWeight: '800',
  },
  summaryListWrap: {
    height: '42%',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 12,
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 13,
    marginTop: 8,
  },
  bottomActions: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
    marginTop: 4,
  },
  actionButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  clearBtn: {
    backgroundColor: '#e53f3f',
  },
  backBtn: {
    backgroundColor: '#0f6dbb',
  },
  actionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalCardEdit: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 22,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#0f5f9f',
    fontSize: 22,
    fontWeight: '800',
  },
  modalOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F2F4F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 10,
  },
  fileButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  fileButtonText: {
    color: '#1f2433',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreviewWrap: {
    width: 66,
    height: 66,
    marginBottom: 8,
  },
  imagePreview: {
    width: 66,
    height: 66,
    borderRadius: 10,
    marginBottom: 8,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#dd4157',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallText: {
    color: '#7a8292',
    fontSize: 12,
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 104,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  errorText: {
    color: '#c2475b',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#1e74c6',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },

  deleteModalCardModern: {
    borderRadius: 24,
    backgroundColor: '#ffffff',
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: 'center',
  },
  deleteIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFE8E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  deleteIconText: {
    fontSize: 26,
  },
  deleteOverline: {
    fontSize: 11,
    color: '#E8453C',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  deleteModalTitle: {
    color: '#1f2433',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#666',
    fontSize: 13,
    lineHeight: 22,
    marginVertical: 14,
    textAlign: 'center',
  },
  deleteModalStrong: {
    color: '#E8453C',
    fontWeight: '800',
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  deleteBtn: {
    minWidth: 130,
    borderRadius: 12,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#1f2433',
    fontSize: 17,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },



  calendarModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pickerTitle: {
    color: '#1a3f6f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f2f4f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    color: '#1a3f6f',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthTitle: {
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  calendarWeekDay: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#f5a623',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  calendarDayCell: {
    width: '14.2857%',
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#f5a623',
  },
  calendarDayText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },

  imageZoomBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.86)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  imageZoomHeader: {
    position: 'absolute',
    top: 48,
    right: 18,
    zIndex: 5,
  },
  imageZoomCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageZoomImage: {
    width: '100%',
    height: '72%',
  },
});
