import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2f4f7',
  },
  header: {
    backgroundColor: '#f5a623',
    paddingTop: 18,
    paddingBottom: 22,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: {
    width: 72,
    height: 72,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoutButton: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.45)',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 90,
  },
  salesCard: {
    backgroundColor: '#1f6fb2',
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  salesTitle: {
    color: 'rgba(255,255,255,0.75)',
    fontWeight: '600',
    fontSize: 12,
  },
  salesValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#1a3f6f',
    fontWeight: '800',
    fontSize: 19,
  },
  sectionLink: {
    color: '#f5a623',
    fontWeight: '700',
    fontSize: 14,
  },
  dateTitle: {
    color: '#e08a00',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 0,
    marginBottom: 0,
  },
  stickyDateHeaderWrap: {
    backgroundColor: '#ffe8c2',
    alignSelf: 'flex-start',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 10,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: '#fff',
    borderRadius: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#f5a623',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  swipeEditAction: {
    marginBottom: 14,
    backgroundColor: '#0f6dbb',
    borderRadius: 12,
    width: 88,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  swipeEditText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  swipeGhostAction: {
    marginBottom: 14,
    width: 24,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#f5a623',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  transactionBody: {
    flex: 1,
  },
  transactionTitle: {
    color: '#8d94a6',
    fontSize: 11,
    fontWeight: '500',
    marginBottom: 1,
  },
  transactionSubtitle: {
    color: '#2563a8',
    fontSize: 14,
    fontWeight: '700',
  },
  amountText: {
    fontSize: 13,
    fontWeight: '800',
  },
  amountIncome: {
    color: '#1a9e5c',
  },
  amountExpense: {
    color: '#c85353',
  },
  amountPill: {
    backgroundColor: '#e8f8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 13,
    marginTop: 10,
  },
  divider: {
    height: 1,
    backgroundColor: '#dfdfec',
    marginVertical: 14,
  },
  registerSaleButton: {
    backgroundColor: '#f5a623',
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    marginTop: 2,
  },
  registerSaleText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 17,
  },
  notificationReportButton: {
    backgroundColor: '#eaf2ff',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#d5e5ff',
  },
  notificationReportButtonText: {
    color: '#2563a8',
    fontWeight: '700',
    fontSize: 15,
  },
  transactionReportButton: {
    backgroundColor: '#fff4e5',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#f0dec0',
  },
  transactionReportButtonText: {
    color: '#e08a00',
    fontWeight: '700',
    fontSize: 15,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e7e7e7',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 20,
  },
  bottomIconWrapActive: {
    width: 56,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#fff0d6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomIconWrap: {
    width: 56,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  headerWave: {
    height: 18,
    backgroundColor: '#f5a623',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 4,
  },

  saleModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  saleModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  saleModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  saleModalTitle: {
    color: '#0f5f9f',
    fontSize: 22,
    fontWeight: '800',
  },
  clientSelect: {
    backgroundColor: '#0f6dbb',
    borderRadius: 12,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  clientSelectText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  readonlyField: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#f2f4f7',
    minHeight: 46,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 10,
  },
  readonlyFieldText: {
    color: '#5f4bb5',
    fontSize: 14,
    fontWeight: '700',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 10,
  },
  fileButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  fileButtonText: {
    color: '#1f2433',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreview: {
    width: 66,
    height: 66,
    borderRadius: 10,
    marginBottom: 8,
  },
  imagePreviewWrap: {
    width: 66,
    height: 66,
    marginBottom: 8,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#dd4157',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallText: {
    color: '#7a8292',
    fontSize: 12,
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 104,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  dateDisplayWrap: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  dateDisplayText: {
    color: '#263143',
    fontSize: 14,
    fontWeight: '600',
  },
  saleErrorText: {
    color: '#c2475b',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#1e74c6',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },


  deleteModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  deleteModalTitle: {
    color: '#0f5f9f',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#3d4352',
    fontSize: 18,
    lineHeight: 30,
    textAlign: 'center',
    marginTop: 14,
    marginBottom: 22,
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
  },
  deleteBtn: {
    flex: 1,
    borderRadius: 26,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#2d3342',
    fontSize: 16,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },


  imageZoomBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.86)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  imageZoomHeader: {
    position: 'absolute',
    top: 48,
    right: 18,
    zIndex: 5,
  },
  imageZoomCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageZoomImage: {
    width: '100%',
    height: '72%',
  },

  clientListCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  clientListTitle: {
    color: '#2f2e67',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  clientSearchInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 10,
    minHeight: 42,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#263143',
    marginBottom: 8,
  },
  clientRow: {
    borderBottomWidth: 1,
    borderBottomColor: '#eceff7',
    paddingVertical: 10,
  },
  clientRowText: {
    color: '#273143',
    fontSize: 14,
    fontWeight: '600',
  },
});
