import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fb',
  },
  header: {
    backgroundColor: '#5b3db3',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: {
    width: 102,
    height: 82,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  logoutButton: {
    backgroundColor: '#7f5ae1',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  logoutText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 90,
  },
  salesCard: {
    backgroundColor: '#6d4ec4',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  salesTitle: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 17,
  },
  salesValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 17,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    color: '#35257c',
    fontWeight: '800',
    fontSize: 18,
  },
  sectionLink: {
    color: '#8f68d9',
    fontWeight: '700',
    fontSize: 18,
  },
  dateTitle: {
    color: '#2f2f50',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 2,
    marginBottom: 6,
  },
  stickyDateHeaderWrap: {
    backgroundColor: '#f5f6fb',
    paddingTop: 4,
    paddingBottom: 2,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#e9d9ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#6746be',
    fontWeight: '700',
    fontSize: 13,
  },
  transactionBody: {
    flex: 1,
  },
  transactionTitle: {
    color: '#293040',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
  },
  transactionSubtitle: {
    color: '#7153c6',
    fontSize: 13,
    fontWeight: '700',
  },
  amountText: {
    fontSize: 15,
    fontWeight: '800',
  },
  amountIncome: {
    color: '#2e9d68',
  },
  amountExpense: {
    color: '#c85353',
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 13,
    marginTop: 10,
  },
  divider: {
    height: 1,
    backgroundColor: '#dfdfec',
    marginVertical: 14,
  },
  registerSaleButton: {
    backgroundColor: '#7c59d7',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 2,
  },
  registerSaleText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#ececf3',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
    paddingBottom: 16,
  },
  bottomIconWrapActive: {
    width: 56,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#7c59d7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomIconWrap: {
    width: 56,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  saleModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  saleModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  saleModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  saleModalTitle: {
    color: '#3b2f7c',
    fontSize: 22,
    fontWeight: '800',
  },
  clientSelect: {
    backgroundColor: '#7b59d7',
    borderRadius: 12,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  clientSelectText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 10,
  },
  fileButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  fileButtonText: {
    color: '#1f2433',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreview: {
    width: 66,
    height: 66,
    borderRadius: 10,
    marginBottom: 8,
  },
  smallText: {
    color: '#7a8292',
    fontSize: 12,
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 104,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  dateDisplayWrap: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  dateDisplayText: {
    color: '#263143',
    fontSize: 14,
    fontWeight: '600',
  },
  saleErrorText: {
    color: '#c2475b',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#bfaef1',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },

  clientListCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  clientListTitle: {
    color: '#2f2e67',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  clientRow: {
    borderBottomWidth: 1,
    borderBottomColor: '#eceff7',
    paddingVertical: 10,
  },
  clientRowText: {
    color: '#273143',
    fontSize: 14,
    fontWeight: '600',
  },
});
