import { StyleSheet } from 'react-native';

export const notificationReportStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#5b3db3',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#7f5ae1', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 20 },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ebe4ff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 10,
  },
  backButtonText: { color: '#3d2f86', fontSize: 13, fontWeight: '700' },
  title: { color: '#35257c', fontSize: 22, fontWeight: '800', marginBottom: 12 },

  filtersRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  filterCol: { flex: 1 },
  filterLabel: { color: '#1f2433', fontSize: 13, fontWeight: '700', marginBottom: 6 },
  dateButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  dateButtonText: { color: '#2a3144', fontSize: 14, fontWeight: '700' },
  webDateInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2a3144',
  },

  sectionLabel: { color: '#1f2433', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  messageBox: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 220,
    maxHeight: 320,
  },
  messageScroll: { flex: 1 },
  messageContent: { padding: 12 },
  messageText: { color: '#2a3144', fontSize: 14, lineHeight: 20 },

  copyButton: {
    marginTop: 12,
    backgroundColor: '#7c59d7',
    borderRadius: 12,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyButtonText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  errorText: { marginTop: 8, color: '#c2475b', fontSize: 13 },
  successText: { marginTop: 8, color: '#2e9d68', fontSize: 13 },
});
