import { StyleSheet } from 'react-native';

export const notificationReportStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F7' },
  header: {
    backgroundColor: '#f59e0b',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#d97706', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { flex: 1, paddingHorizontal: 20, paddingTop: 14, paddingBottom: 20 },
  titleWrap: { marginBottom: 14 },
  titleOverline: {
    color: '#F5A623',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  title: { color: '#1A3F6F', fontSize: 24, fontWeight: '800', marginBottom: 6 },
  filtersCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#eceff5',
    padding: 14,
    marginBottom: 12,
  },

  filtersRow: { flexDirection: 'row', gap: 10 },
  filterCol: { flex: 1 },
  filterLabel: { color: '#1A3F6F', fontSize: 12, fontWeight: '700', marginBottom: 6 },
  dateButton: {
    borderWidth: 1.5,
    borderColor: '#eee',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  dateButtonText: { color: '#1A3F6F', fontSize: 13, fontWeight: '700' },
  webDateInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2a3144',
  },

  sectionLabel: { color: '#1A3F6F', fontSize: 14, fontWeight: '700', marginBottom: 6 },
  messageBox: {
    borderWidth: 1,
    borderColor: '#e8ecf4',
    borderRadius: 16,
    backgroundColor: '#fff',
    minHeight: 220,
    maxHeight: 320,
  },
  messageScroll: { flex: 1 },
  messageContent: { padding: 12 },
  messageText: { color: '#2a3144', fontSize: 14, lineHeight: 20 },

  copyButton: {
    marginTop: 12,
    backgroundColor: '#F5A623',
    borderRadius: 16,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyButtonDone: { backgroundColor: '#1A9E5C' },
  copyButtonText: { color: '#fff', fontSize: 16, fontWeight: '800' },

  backButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#EAF2FF',
    borderRadius: 16,
    minHeight: 50,
    marginTop: 10,
  },
  backButtonText: { color: '#2563A8', fontSize: 15, fontWeight: '800' },
  errorText: { marginTop: 8, color: '#c2475b', fontSize: 13 },

  calendarBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  calendarModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pickerTitle: {
    color: '#1a3f6f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f2f4f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    color: '#1a3f6f',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthTitle: {
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  calendarWeekDay: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#f5a623',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  calendarDayCell: {
    width: '14.2857%',
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#f5a623',
  },
  calendarDayText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },
});
