import { StyleSheet } from 'react-native';

export const transactionsFilterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f6fb',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 110,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  miniLogo: {
    width: 24,
    height: 24,
    borderRadius: 6,
  },
  closeBtn: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#252a38',
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 16,
  },
  datesRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  dateInputButton: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ef',
    borderWidth: 1,
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  dateInputButtonText: {
    fontSize: 16,
    color: '#273143',
  },
  webDateInput: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ef',
    borderWidth: 1,
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#273143',
  },
  clientInput: {
    backgroundColor: '#ffffff',
    borderColor: '#dfe3ef',
    borderWidth: 1,
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 14,
    fontSize: 16,
    color: '#273143',
    marginBottom: 12,
  },
  salesCard: {
    backgroundColor: '#6d4ec4',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  salesTitle: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 17,
  },
  salesValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 17,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#f5f6fb',
  },
  swipeGhostAction: {
    marginBottom: 16,
    width: 24,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#e9d9ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#6746be',
    fontWeight: '700',
    fontSize: 13,
  },
  body: {
    flex: 1,
  },
  titleText: {
    color: '#293040',
    fontSize: 16,
    fontWeight: '800',
  },
  subtitleText: {
    color: '#7153c6',
    fontSize: 13,
    fontWeight: '700',
  },
  dateText: {
    color: '#6f7383',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  amountIncome: {
    color: '#2e9d68',
    fontSize: 15,
    fontWeight: '800',
  },
  amountExpense: {
    color: '#c85353',
    fontSize: 15,
    fontWeight: '800',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 20,
  },
  emptyText: {
    color: '#666b7a',
    fontSize: 14,
    marginTop: 8,
  },
  bottomActions: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 22,
    flexDirection: 'row',
    gap: 10,
  },
  actionButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  clearBtn: {
    backgroundColor: '#e53f3f',
  },
  backBtn: {
    backgroundColor: '#7c59d7',
  },
  actionText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },


  deleteModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  deleteModalTitle: {
    color: '#3b2f7c',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#3d4352',
    fontSize: 18,
    lineHeight: 30,
    textAlign: 'center',
    marginTop: 14,
    marginBottom: 22,
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
  },
  deleteBtn: {
    flex: 1,
    borderRadius: 26,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#2d3342',
    fontSize: 16,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },


  imageZoomBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.86)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  imageZoomHeader: {
    position: 'absolute',
    top: 48,
    right: 18,
    zIndex: 5,
  },
  imageZoomCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageZoomImage: {
    width: '100%',
    height: '72%',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#3b2f7c',
    fontSize: 22,
    fontWeight: '800',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  readonlyField: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#f5f6fb',
    minHeight: 46,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 10,
  },
  readonlyFieldText: {
    color: '#5f4bb5',
    fontSize: 14,
    fontWeight: '700',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 10,
  },
  fileButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  fileButtonText: {
    color: '#1f2433',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreviewWrap: {
    width: 66,
    height: 66,
    marginBottom: 8,
  },
  imagePreview: {
    width: 66,
    height: 66,
    borderRadius: 10,
    marginBottom: 8,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#dd4157',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallText: {
    color: '#7a8292',
    fontSize: 12,
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 104,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  errorText: {
    color: '#c2475b',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#bfaef1',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },
});
