import { StyleSheet } from 'react-native';

export const transactionReportStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#5b3db3',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#7f5ae1', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 24 },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ebe4ff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 10,
  },
  backButtonText: { color: '#3d2f86', fontSize: 13, fontWeight: '700' },
  title: { color: '#35257c', fontSize: 22, fontWeight: '800', marginBottom: 10 },

  filtersCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e3e6f1',
    padding: 12,
    marginBottom: 10,
  },
  filterLabel: { color: '#1f2433', fontSize: 13, fontWeight: '700', marginBottom: 6, marginTop: 4 },
  dateButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#fff',
  },
  dateButtonText: { color: '#2a3144', fontSize: 14, fontWeight: '700' },
  webDateInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2a3144',
  },
  typeButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#fff',
  },
  typeButtonText: { color: '#2a3144', fontSize: 14 },
  typeList: { borderWidth: 1, borderColor: '#dfe3ef', borderRadius: 12, marginTop: 6 },
  typeItem: { paddingHorizontal: 12, paddingVertical: 10 },
  typeItemText: { color: '#2a3144', fontSize: 14 },

  sectionTitle: { color: '#11182b', fontSize: 18, fontWeight: '800', marginTop: 4 },
  sectionSubtitle: { color: '#5d6477', fontSize: 13, marginTop: 2, marginBottom: 10 },
  summaryGrid: { marginBottom: 12 },
  summaryGridRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  summarySingleWrap: { marginBottom: 12 },
  summaryCard: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d9dce8',
    backgroundColor: '#fff',
    padding: 12,
  },
  summaryLabel: { color: '#1f2433', fontSize: 16, fontWeight: '700' },
  summaryAmount: { color: '#0f172a', fontSize: 24, fontWeight: '800', marginTop: 6 },
  summaryCardGrid: { width: '48%' },

  resultsTitle: { color: '#11182b', fontSize: 20, fontWeight: '800' },
  resultsSubtitle: { color: '#5d6477', fontSize: 13, marginTop: 2, marginBottom: 8 },
  searchBox: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  searchInput: { flex: 1, marginLeft: 8, color: '#2a3144', fontSize: 15 },

  cardsWrap: { marginBottom: 12, gap: 10 },
  transactionCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    padding: 12,
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 6,
  },
  cardLabel: { color: '#596175', fontSize: 13, fontWeight: '700' },
  cardValue: { color: '#11182b', fontSize: 14, fontWeight: '600', flex: 1, textAlign: 'right' },
  cardNotesBlock: { marginTop: 4 },
  cardNotes: { color: '#11182b', fontSize: 14, lineHeight: 19, marginTop: 4 },

  emptyText: { color: '#666b7a', fontSize: 13, paddingVertical: 12 },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
});
