import { StyleSheet } from 'react-native';

export const transactionReportStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f6fb' },
  header: {
    backgroundColor: '#5b3db3',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#7f5ae1', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  content: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 24 },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ebe4ff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 10,
  },
  backButtonText: { color: '#3d2f86', fontSize: 13, fontWeight: '700' },
  title: { color: '#35257c', fontSize: 22, fontWeight: '800', marginBottom: 10 },

  filtersCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e3e6f1',
    padding: 12,
    marginBottom: 10,
  },
  filterLabel: { color: '#1f2433', fontSize: 13, fontWeight: '700', marginBottom: 6, marginTop: 4 },
  dateButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#fff',
  },
  dateButtonText: { color: '#2a3144', fontSize: 14, fontWeight: '700' },
  webDateInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2a3144',
  },
  typeButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
    backgroundColor: '#fff',
  },
  typeButtonText: { color: '#2a3144', fontSize: 14 },
  typeList: { borderWidth: 1, borderColor: '#dfe3ef', borderRadius: 12, marginTop: 6 },
  typeItem: { paddingHorizontal: 12, paddingVertical: 10 },
  typeItemText: { color: '#2a3144', fontSize: 14 },

  sectionTitle: { color: '#11182b', fontSize: 18, fontWeight: '800', marginTop: 4 },
  sectionSubtitle: { color: '#5d6477', fontSize: 13, marginTop: 2, marginBottom: 10 },
  summaryScroll: { marginBottom: 12 },
  summaryCard: {
    width: 220,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d9dce8',
    backgroundColor: '#fff',
    padding: 12,
    marginRight: 10,
  },
  summaryLabel: { color: '#1f2433', fontSize: 16, fontWeight: '700' },
  summaryAmount: { color: '#0f172a', fontSize: 38, fontWeight: '800', marginTop: 6 },

  resultsTitle: { color: '#11182b', fontSize: 20, fontWeight: '800' },
  resultsSubtitle: { color: '#5d6477', fontSize: 13, marginTop: 2, marginBottom: 8 },
  searchBox: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  searchInput: { flex: 1, marginLeft: 8, color: '#2a3144', fontSize: 15 },

  tableWrap: { marginBottom: 12 },
  table: { minWidth: 980, backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#dfe3ef' },
  tableHeaderRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#dfe3ef', backgroundColor: '#f9fafc' },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#edf0f8' },
  headerCell: { color: '#596175', fontSize: 15, fontWeight: '700', paddingVertical: 12, paddingHorizontal: 12 },
  bodyCell: { color: '#11182b', fontSize: 15, paddingVertical: 12, paddingHorizontal: 12 },
  typeValue: { fontWeight: '800' },
  cellType: { width: 200 },
  cellClient: { width: 200 },
  cellDate: { width: 150 },
  cellAmount: { width: 120 },
  cellNotes: { width: 310 },

  emptyText: { color: '#666b7a', fontSize: 13, padding: 12 },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },
});
