import { StyleSheet } from 'react-native';

export const transactionReportStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F2F4F7' },
  header: {
    backgroundColor: '#f59e0b',
    paddingTop: 22,
    paddingBottom: 18,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoBox: { width: 102, height: 82, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  logoImage: { width: '100%', height: '100%' },
  logoutButton: { backgroundColor: '#d97706', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 10 },
  logoutText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  keyboardAvoidingWrap: { flex: 1 },
  content: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 20 },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  titleOverline: {
    fontSize: 11,
    color: '#F5A623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 1,
  },
  title: { fontSize: 22, fontWeight: '800', color: '#1A3F6F' },
  backButtonTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EAF2FF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginTop: 4,
  },
  backButtonTopIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1A3F6F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonTopText: {
    color: '#1A3F6F',
    fontWeight: '700',
    fontSize: 12,
  },

  filtersCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#eceff5',
    marginBottom: 14,
  },
  filtersRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  filterCol: { flex: 1 },
  filterLabel: { color: '#1A3F6F', fontSize: 11, fontWeight: '700', marginBottom: 5 },
  dateButton: {
    borderWidth: 1.5,
    borderColor: '#eee',
    borderRadius: 12,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 13,
    backgroundColor: '#fff',
  },
  dateButtonText: { color: '#1A3F6F', fontSize: 12, fontWeight: '600' },
  webDateInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#fff',
    minHeight: 44,
    paddingHorizontal: 14,
    fontSize: 14,
    color: '#2a3144',
  },
  typeChipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  typeChip: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#F2F4F7',
  },
  typeChipActive: {
    backgroundColor: '#F5A623',
  },
  typeChipText: {
    color: '#555',
    fontSize: 11,
    fontWeight: '700',
  },
  typeChipTextActive: {
    color: '#fff',
  },

  summarySection: { marginBottom: 14 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#1A3F6F', marginBottom: 3 },
  sectionSubtitle: { fontSize: 11, color: '#999', marginBottom: 10 },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 8,
    marginBottom: 8,
  },
  summaryCard: {
    width: '48.5%',
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 3,
  },
  summaryLabel: { fontSize: 11, fontWeight: '700', marginBottom: 4 },
  summaryAmount: { fontSize: 18, fontWeight: '800', color: '#1A3F6F' },
  grandTotalCard: {
    backgroundColor: '#F5A623',
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  grandTotalLabel: { color: '#fff', fontWeight: '700', fontSize: 13 },
  grandTotalAmount: { color: '#fff', fontWeight: '800', fontSize: 20 },

  resultsTitle: { fontSize: 13, fontWeight: '800', color: '#1A3F6F', marginBottom: 2 },
  resultsSubtitle: { fontSize: 11, color: '#999', marginBottom: 10 },
  searchBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    minHeight: 42,
    borderWidth: 1.5,
    borderColor: '#eee',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchInput: { flex: 1, color: '#333', fontSize: 12 },
  searchClear: { opacity: 0.4, fontSize: 13 },

  cardsWrap: { gap: 8, marginBottom: 8 },
  transactionCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#F5A623',
  },
  txMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  txAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F5A623',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txAvatarText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 12,
  },
  txMainBody: { flex: 1, minWidth: 0 },
  txEmpName: {
    color: '#1A3F6F',
    fontWeight: '800',
    fontSize: 13,
  },
  txDate: {
    fontSize: 11,
    color: '#bbb',
  },
  txRightCol: {
    alignItems: 'flex-end',
    gap: 4,
  },
  txAmount: {
    color: '#1A9E5C',
    fontWeight: '800',
    fontSize: 14,
  },
  txTypePill: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  txTypePillText: {
    fontSize: 10,
    fontWeight: '700',
  },
  txExpandIcon: {
    fontSize: 12,
    color: '#bbb',
  },

  txDetailsWrap: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  txDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 6,
    marginBottom: 8,
  },
  txDetailItem: {
    width: '48.5%',
    backgroundColor: '#F8F9FB',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  txDetailLabel: {
    fontSize: 9,
    color: '#aaa',
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  txDetailValue: {
    fontSize: 12,
    color: '#1A3F6F',
    fontWeight: '700',
  },
  txNotesBox: {
    backgroundColor: '#FFFBF0',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#F5A62322',
  },
  txNotesLabel: {
    fontSize: 9,
    color: '#E08A00',
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 3,
  },
  txNotesText: {
    fontSize: 12,
    color: '#555',
    lineHeight: 18,
  },

  emptyText: { color: '#666b7a', fontSize: 13, paddingVertical: 12, textAlign: 'center' },
  errorText: { color: '#c2475b', fontSize: 13, marginBottom: 8 },

  calendarBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  calendarModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pickerTitle: {
    color: '#1a3f6f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  calendarNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f2f4f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    color: '#1a3f6f',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthTitle: {
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  calendarWeekDay: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#f5a623',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  calendarDayCell: {
    width: '14.2857%',
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#f5a623',
  },
  calendarDayText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },
});
