import { StyleSheet } from 'react-native';

export const transactionsFilterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2f4f7',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 124,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportLabel: {
    fontSize: 11,
    color: '#f5a623',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  title: {
    color: '#1a3f6f',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 14,
  },
  datesRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  dateCol: {
    flex: 1,
  },
  filterLabel: {
    fontSize: 10,
    color: '#9aa0ad',
    fontWeight: '600',
    marginBottom: 4,
    paddingLeft: 4,
  },
  dateInputButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderColor: '#eeeeee',
    borderWidth: 1.5,
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 14,
  },
  dateInputButtonIcon: {
    fontSize: 14,
  },
  dateInputButtonText: {
    fontSize: 13,
    color: '#1a3f6f',
    fontWeight: '600',
  },
  webDateInput: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#ffffff',
    borderColor: '#eeeeee',
    borderWidth: 1.5,
    borderRadius: 12,
    height: 48,
    paddingHorizontal: 14,
    fontSize: 13,
    color: '#1a3f6f',
    fontWeight: '600',
  },
  searchWrap: {
    backgroundColor: '#ffffff',
    borderColor: '#eeeeee',
    borderWidth: 1.5,
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  clientInput: {
    flex: 1,
    fontSize: 14,
    color: '#273143',
  },
  salesCard: {
    backgroundColor: '#f5a623',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#f5a623',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  salesLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  salesIcon: {
    fontSize: 18,
  },
  salesTitle: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 17,
  },
  salesRight: {
    alignItems: 'flex-end',
  },
  salesHint: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 10,
    fontWeight: '600',
  },
  salesValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#f5a623',
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  swipeGhostAction: {
    marginBottom: 8,
    width: 24,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f5a623',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 13,
  },
  body: {
    flex: 1,
    minWidth: 0,
  },
  titleText: {
    color: '#9a9a9a',
    fontSize: 11,
    fontWeight: '500',
  },
  subtitleText: {
    color: '#2563a8',
    fontSize: 13,
    fontWeight: '700',
  },
  dateText: {
    color: '#b8bdc9',
    fontSize: 10,
    marginTop: 1,
  },
  amountPill: {
    backgroundColor: '#e8f8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginLeft: 8,
  },
  amountIncome: {
    color: '#1a9e5c',
    fontSize: 12,
    fontWeight: '800',
  },
  amountExpense: {
    color: '#c85353',
    fontSize: 12,
    fontWeight: '800',
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 8,
  },
  emptyText: {
    color: '#a2a9b9',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 26,
  },
  bottomActions: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  actionButton: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  clearBtn: {
    backgroundColor: '#e8453c',
  },
  backBtn: {
    backgroundColor: '#1a3f6f',
  },
  actionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },


  calendarModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pickerTitle: {
    color: '#1a3f6f',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
  },
  pickerActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 8,
  },


  calendarNavRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  calendarNavBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f2f4f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarNavBtnText: {
    color: '#1a3f6f',
    fontSize: 18,
    fontWeight: '700',
    marginTop: -2,
  },
  calendarMonthTitle: {
    color: '#1a3f6f',
    fontSize: 14,
    fontWeight: '800',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 6,
  },
  calendarWeekDay: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#f5a623',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 6,
  },
  calendarDayCell: {
    width: '14.2857%',
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  calendarDayCellSelected: {
    backgroundColor: '#f5a623',
  },
  calendarDayText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '800',
  },

  deleteModalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  deleteModalTitle: {
    color: '#0f5f9f',
    fontSize: 22,
    fontWeight: '800',
  },
  deleteModalMessage: {
    color: '#3d4352',
    fontSize: 18,
    lineHeight: 30,
    textAlign: 'center',
    marginTop: 14,
    marginBottom: 22,
  },
  deleteActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 14,
  },
  deleteBtn: {
    flex: 1,
    borderRadius: 26,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteCancelBtn: {
    borderWidth: 1,
    borderColor: '#dfdfec',
    backgroundColor: '#ffffff',
  },
  deleteConfirmBtn: {
    backgroundColor: '#ef4040',
  },
  deleteCancelText: {
    color: '#2d3342',
    fontSize: 16,
    fontWeight: '700',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },


  imageZoomBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.86)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  imageZoomHeader: {
    position: 'absolute',
    top: 48,
    right: 18,
    zIndex: 5,
  },
  imageZoomCloseBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageZoomImage: {
    width: '100%',
    height: '72%',
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  modalCard: {
    borderRadius: 14,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#0f5f9f',
    fontSize: 22,
    fontWeight: '800',
  },
  fieldLabel: {
    color: '#1f2433',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  readonlyField: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#f5f6fb',
    minHeight: 46,
    paddingHorizontal: 14,
    justifyContent: 'center',
    marginBottom: 10,
  },
  readonlyFieldText: {
    color: '#5f4bb5',
    fontSize: 14,
    fontWeight: '700',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    minHeight: 46,
    paddingHorizontal: 14,
    fontSize: 15,
    color: '#263143',
    marginBottom: 10,
  },
  fileButton: {
    borderWidth: 1,
    borderColor: '#dfe3ef',
    borderRadius: 12,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  fileButtonText: {
    color: '#1f2433',
    fontSize: 14,
    fontWeight: '700',
  },
  imagePreviewWrap: {
    width: 66,
    height: 66,
    marginBottom: 8,
  },
  imagePreview: {
    width: 66,
    height: 66,
    borderRadius: 10,
    marginBottom: 8,
  },
  removeImageBtn: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#dd4157',
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallText: {
    color: '#7a8292',
    fontSize: 12,
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 104,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  errorText: {
    color: '#c2475b',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  modalActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  modalActionBtn: {
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  modalConfirmBtn: {
    backgroundColor: '#1e74c6',
  },
  modalCancelBtn: {
    backgroundColor: '#ffffff',
  },
  modalActionBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  modalCancelBtnText: {
    color: '#2f2e67',
    fontWeight: '800',
    fontSize: 14,
  },
});
